import 'admin_models.dart';

// ─── Mock Users ──────────────────────────────────────────────────────────────

final List<AppUser> mockUsers = [
  AppUser(
    id: 'u1',
    nombres: 'Alejandro',
    apellidos: 'Martínez Huanca',
    dni: '45213678',
    email: 'a.martinez@diresapuno.gob.pe',
    telefono: '951 234 567',
    rol: UserRole.medico,
    area: 'Medicina General',
    establecimiento: 'C.S. Juliaca',
    estado: UserStatus.activo,
    cmp: '78542',
    username: 'dr.martinez',
    lastAccess: DateTime(2026, 6, 10, 8, 1),
    fechaNacimiento: DateTime(1984, 3, 15),
    sexo: 'Masculino',
    cargo: 'Médico Asistencial',
  ),
  AppUser(
    id: 'u2',
    nombres: 'Patricia',
    apellidos: 'Quispe Mamani',
    dni: '38547621',
    email: 'p.quispe@diresapuno.gob.pe',
    telefono: '952 345 678',
    rol: UserRole.medico,
    area: 'Pediatría',
    establecimiento: 'C.S. Juliaca',
    estado: UserStatus.activo,
    cmp: '61238',
    username: 'dra.quispe',
    lastAccess: DateTime(2026, 6, 10, 7, 55),
    fechaNacimiento: DateTime(1987, 7, 22),
    sexo: 'Femenino',
    cargo: 'Médico Pediatra',
  ),
  AppUser(
    id: 'u3',
    nombres: 'Roberto',
    apellidos: 'Flores Cano',
    dni: '29874512',
    email: 'r.flores@diresapuno.gob.pe',
    telefono: '953 456 789',
    rol: UserRole.medico,
    area: 'Ginecología',
    establecimiento: 'C.S. Juliaca',
    estado: UserStatus.activo,
    cmp: '52341',
    username: 'dr.flores',
    lastAccess: DateTime(2026, 6, 9, 17, 30),
    fechaNacimiento: DateTime(1980, 11, 5),
    sexo: 'Masculino',
    cargo: 'Médico Ginecólogo',
  ),
  AppUser(
    id: 'u4',
    nombres: 'Sandra',
    apellidos: 'Condori Apaza',
    dni: '47896523',
    email: 's.condori@diresapuno.gob.pe',
    telefono: '954 567 890',
    rol: UserRole.medico,
    area: 'Emergencia',
    establecimiento: 'C.S. Juliaca',
    estado: UserStatus.activo,
    cmp: '83691',
    username: 'dra.condori',
    lastAccess: DateTime(2026, 6, 10, 6, 45),
    fechaNacimiento: DateTime(1990, 1, 18),
    sexo: 'Femenino',
    cargo: 'Médico Emergenciólogo',
  ),
  AppUser(
    id: 'u5',
    nombres: 'Marco',
    apellidos: 'Larico Puma',
    dni: '36521478',
    email: 'm.larico@diresapuno.gob.pe',
    telefono: '955 678 901',
    rol: UserRole.medico,
    area: 'Cardiología',
    establecimiento: 'P.S. Lampa',
    estado: UserStatus.inactivo,
    cmp: '44127',
    username: 'dr.larico',
    lastAccess: DateTime(2026, 5, 28, 14, 15),
    fechaNacimiento: DateTime(1978, 9, 30),
    sexo: 'Masculino',
    cargo: 'Médico Cardiólogo',
  ),
  AppUser(
    id: 'u6',
    nombres: 'Carmen',
    apellidos: 'Ramos Ticona',
    dni: '52364178',
    email: 'c.ramos@diresapuno.gob.pe',
    telefono: '956 789 012',
    rol: UserRole.enfermero,
    area: 'Medicina General',
    establecimiento: 'C.S. Juliaca',
    estado: UserStatus.activo,
    colegiatura: 'CEP-15423',
    username: 'enf.ramos',
    lastAccess: DateTime(2026, 6, 10, 8, 10),
    fechaNacimiento: DateTime(1992, 4, 12),
    sexo: 'Femenino',
    cargo: 'Enfermera Asistencial',
  ),
  AppUser(
    id: 'u7',
    nombres: 'Jorge',
    apellidos: 'Mamani Chura',
    dni: '41523698',
    email: 'j.mamani@diresapuno.gob.pe',
    telefono: '957 890 123',
    rol: UserRole.enfermero,
    area: 'Emergencia',
    establecimiento: 'C.S. Juliaca',
    estado: UserStatus.activo,
    colegiatura: 'CEP-28741',
    username: 'enf.mamani',
    lastAccess: DateTime(2026, 6, 10, 7, 0),
    fechaNacimiento: DateTime(1995, 8, 25),
    sexo: 'Masculino',
    cargo: 'Enfermero Emergencias',
  ),
  AppUser(
    id: 'u8',
    nombres: 'Luis',
    apellidos: 'Torres Sánchez',
    dni: '63254178',
    email: 'l.torres@diresapuno.gob.pe',
    telefono: '958 901 234',
    rol: UserRole.administrativo,
    area: 'Admisión',
    establecimiento: 'C.S. Juliaca',
    estado: UserStatus.activo,
    username: 'adm.torres',
    lastAccess: DateTime(2026, 6, 10, 8, 5),
    fechaNacimiento: DateTime(1988, 6, 3),
    sexo: 'Masculino',
    cargo: 'Técnico Administrativo',
  ),
  AppUser(
    id: 'u9',
    nombres: 'Rosa',
    apellidos: 'Ccopa Huanca',
    dni: '74512369',
    email: 'r.ccopa@diresapuno.gob.pe',
    telefono: '959 012 345',
    rol: UserRole.administrativo,
    area: 'Farmacia',
    establecimiento: 'P.S. Azángaro',
    estado: UserStatus.suspendido,
    username: 'adm.ccopa',
    lastAccess: DateTime(2026, 5, 15, 12, 30),
    fechaNacimiento: DateTime(1993, 12, 8),
    sexo: 'Femenino',
    cargo: 'Técnico Farmacia',
  ),
  AppUser(
    id: 'u10',
    nombres: 'Víctor',
    apellidos: 'Pari Quispe',
    dni: '85412369',
    email: 'v.pari@diresapuno.gob.pe',
    telefono: '960 123 456',
    rol: UserRole.administrador,
    area: 'Administración',
    establecimiento: 'C.S. Juliaca',
    estado: UserStatus.activo,
    username: 'admin.pari',
    lastAccess: DateTime(2026, 6, 10, 7, 58),
    fechaNacimiento: DateTime(1982, 2, 14),
    sexo: 'Masculino',
    cargo: 'Administrador del Sistema',
  ),
  AppUser(
    id: 'u11',
    nombres: 'Ana',
    apellidos: 'Catacora Lupaca',
    dni: '59632147',
    email: 'a.catacora@diresapuno.gob.pe',
    telefono: '961 234 567',
    rol: UserRole.auditor,
    area: 'Administración',
    establecimiento: 'C.S. Juliaca',
    estado: UserStatus.activo,
    username: 'aud.catacora',
    lastAccess: DateTime(2026, 6, 9, 16, 45),
    fechaNacimiento: DateTime(1986, 10, 20),
    sexo: 'Femenino',
    cargo: 'Auditora de Sistemas',
  ),
  AppUser(
    id: 'u12',
    nombres: 'Pedro',
    apellidos: 'Apaza Mamani',
    dni: '32145698',
    email: 'p.apaza@diresapuno.gob.pe',
    telefono: '962 345 678',
    rol: UserRole.administrativo,
    area: 'Laboratorio',
    establecimiento: 'P.S. Lampa',
    estado: UserStatus.inactivo,
    username: 'adm.apaza',
    lastAccess: DateTime(2026, 4, 20, 10, 0),
    fechaNacimiento: DateTime(1991, 5, 17),
    sexo: 'Masculino',
    cargo: 'Técnico Laboratorio',
  ),
];

// ─── Mock Roles & Permissions ────────────────────────────────────────────────

final List<String> moduleNames = [
  'Dashboard',
  'Pacientes',
  'Historias Clínicas',
  'Consultas',
  'Telemedicina',
  'Recetas',
  'Reportes',
  'Administración',
];

List<ModulePermission> _buildPermissions(Map<String, List<String>> config) {
  return moduleNames.map((mod) {
    final perms = config[mod] ?? [];
    return ModulePermission(
      module: mod,
      ver: perms.contains('ver'),
      crear: perms.contains('crear'),
      editar: perms.contains('editar'),
      eliminar: perms.contains('eliminar'),
      exportar: perms.contains('exportar'),
      aprobarFirmar: perms.contains('aprobar'),
    );
  }).toList();
}

final List<RoleDefinition> mockRoles = [
  RoleDefinition(
    role: UserRole.medico,
    permissions: _buildPermissions({
      'Dashboard': ['ver', 'exportar'],
      'Pacientes': ['ver', 'crear', 'editar', 'exportar'],
      'Historias Clínicas': ['ver', 'crear', 'editar', 'exportar', 'aprobar'],
      'Consultas': ['ver', 'crear', 'editar', 'aprobar'],
      'Telemedicina': ['ver', 'crear', 'editar'],
      'Recetas': ['ver', 'crear', 'editar', 'aprobar'],
      'Reportes': ['ver', 'exportar'],
      'Administración': [],
    }),
  ),
  RoleDefinition(
    role: UserRole.enfermero,
    permissions: _buildPermissions({
      'Dashboard': ['ver'],
      'Pacientes': ['ver', 'editar'],
      'Historias Clínicas': ['ver', 'editar'],
      'Consultas': ['ver', 'crear'],
      'Telemedicina': ['ver'],
      'Recetas': ['ver'],
      'Reportes': ['ver'],
      'Administración': [],
    }),
  ),
  RoleDefinition(
    role: UserRole.administrativo,
    permissions: _buildPermissions({
      'Dashboard': ['ver'],
      'Pacientes': ['ver', 'crear', 'editar'],
      'Historias Clínicas': ['ver'],
      'Consultas': ['ver'],
      'Telemedicina': ['ver'],
      'Recetas': ['ver'],
      'Reportes': ['ver', 'exportar'],
      'Administración': [],
    }),
  ),
  RoleDefinition(
    role: UserRole.auditor,
    permissions: _buildPermissions({
      'Dashboard': ['ver', 'exportar'],
      'Pacientes': ['ver'],
      'Historias Clínicas': ['ver'],
      'Consultas': ['ver'],
      'Telemedicina': ['ver'],
      'Recetas': ['ver'],
      'Reportes': ['ver', 'exportar'],
      'Administración': ['ver', 'exportar'],
    }),
  ),
  RoleDefinition(
    role: UserRole.administrador,
    permissions: _buildPermissions({
      'Dashboard': ['ver', 'exportar'],
      'Pacientes': ['ver', 'crear', 'editar', 'eliminar', 'exportar'],
      'Historias Clínicas': [
        'ver',
        'crear',
        'editar',
        'eliminar',
        'exportar',
        'aprobar',
      ],
      'Consultas': ['ver', 'crear', 'editar', 'eliminar', 'exportar', 'aprobar'],
      'Telemedicina': ['ver', 'crear', 'editar', 'eliminar'],
      'Recetas': ['ver', 'crear', 'editar', 'eliminar', 'exportar', 'aprobar'],
      'Reportes': ['ver', 'crear', 'editar', 'eliminar', 'exportar'],
      'Administración': [
        'ver',
        'crear',
        'editar',
        'eliminar',
        'exportar',
        'aprobar',
      ],
    }),
  ),
];

// ─── Mock Medical Areas ───────────────────────────────────────────────────────

final List<MedicalArea> mockAreas = [
  MedicalArea(
    id: 'a1',
    nombre: 'Medicina General',
    codigo: 'MG-01',
    descripcion: 'Atención de salud integral para pacientes adultos',
    responsable: 'Dr. Alejandro Martínez',
    personalAsignado: 4,
    estado: AreaStatus.activa,
    horario: 'Lun–Vie 07:30 – 13:30 / 14:30 – 17:30',
  ),
  MedicalArea(
    id: 'a2',
    nombre: 'Pediatría',
    codigo: 'PED-01',
    descripcion: 'Atención médica especializada para niños de 0 a 14 años',
    responsable: 'Dra. Patricia Quispe',
    personalAsignado: 3,
    estado: AreaStatus.activa,
    horario: 'Lun–Vie 07:30 – 13:30',
  ),
  MedicalArea(
    id: 'a3',
    nombre: 'Ginecología',
    codigo: 'GIN-01',
    descripcion: 'Atención en salud reproductiva y obstétrica',
    responsable: 'Dr. Roberto Flores',
    personalAsignado: 2,
    estado: AreaStatus.activa,
    horario: 'Lun–Vie 08:00 – 14:00',
  ),
  MedicalArea(
    id: 'a4',
    nombre: 'Emergencia',
    codigo: 'EMR-01',
    descripcion: 'Atención de urgencias y emergencias médicas 24/7',
    responsable: 'Dra. Sandra Condori',
    personalAsignado: 6,
    estado: AreaStatus.activa,
    horario: 'Las 24 horas, todos los días',
  ),
  MedicalArea(
    id: 'a5',
    nombre: 'Cardiología',
    codigo: 'CAR-01',
    descripcion: 'Diagnóstico y tratamiento de enfermedades cardiovasculares',
    responsable: 'Dr. Marco Larico',
    personalAsignado: 2,
    estado: AreaStatus.inactiva,
    horario: 'Mar y Jue 08:00 – 12:00',
  ),
  MedicalArea(
    id: 'a6',
    nombre: 'Telemedicina',
    codigo: 'TEL-01',
    descripcion: 'Consultas médicas virtuales y teleconsultas especializadas',
    responsable: 'Dr. Alejandro Martínez',
    personalAsignado: 3,
    estado: AreaStatus.activa,
    horario: 'Lun–Vie 09:00 – 12:00',
  ),
  MedicalArea(
    id: 'a7',
    nombre: 'Farmacia',
    codigo: 'FAR-01',
    descripcion: 'Dispensación de medicamentos y gestión de stock farmacéutico',
    responsable: 'Tec. Rosa Ccopa',
    personalAsignado: 2,
    estado: AreaStatus.activa,
    horario: 'Lun–Sáb 07:00 – 19:00',
  ),
  MedicalArea(
    id: 'a8',
    nombre: 'Laboratorio',
    codigo: 'LAB-01',
    descripcion: 'Análisis clínicos y pruebas diagnósticas',
    responsable: 'Tec. Pedro Apaza',
    personalAsignado: 2,
    estado: AreaStatus.activa,
    horario: 'Lun–Vie 07:30 – 14:00',
  ),
  MedicalArea(
    id: 'a9',
    nombre: 'Admisión',
    codigo: 'ADM-01',
    descripcion: 'Registro, admisión y orientación al paciente',
    responsable: 'Adm. Luis Torres',
    personalAsignado: 3,
    estado: AreaStatus.activa,
    horario: 'Lun–Sáb 07:00 – 17:00',
  ),
];

// ─── Mock Establishments ─────────────────────────────────────────────────────

final List<Establishment> mockEstablishments = [
  Establishment(
    id: 'e1',
    nombre: 'Centro de Salud Juliaca',
    codigoRenipress: 'REP-2301-001',
    red: 'Red de Salud San Román',
    microred: 'Microred Juliaca Norte',
    distrito: 'Juliaca',
    provincia: 'San Román',
    departamento: 'Puno',
    responsable: 'Dr. Alejandro Martínez',
    telefono: '051 321 456',
    activo: true,
  ),
  Establishment(
    id: 'e2',
    nombre: 'Puesto de Salud Lampa',
    codigoRenipress: 'REP-2302-014',
    red: 'Red de Salud Lampa',
    microred: 'Microred Lampa',
    distrito: 'Lampa',
    provincia: 'Lampa',
    departamento: 'Puno',
    responsable: 'Dra. Sandra Condori',
    telefono: '051 456 789',
    activo: true,
  ),
  Establishment(
    id: 'e3',
    nombre: 'Puesto de Salud Azángaro',
    codigoRenipress: 'REP-2303-022',
    red: 'Red de Salud Azángaro',
    microred: 'Microred Azángaro Centro',
    distrito: 'Azángaro',
    provincia: 'Azángaro',
    departamento: 'Puno',
    responsable: 'Dra. Patricia Quispe',
    telefono: '051 567 890',
    activo: false,
  ),
];

// ─── Mock Audit Records ───────────────────────────────────────────────────────

final List<AuditRecord> mockAuditRecords = [
  AuditRecord(
    id: 'aud1',
    usuario: 'Dr. Alejandro Martínez',
    usuarioRol: 'Médico',
    accion: AuditActionType.login,
    modulo: 'Sistema',
    detalle: 'Inicio de sesión exitoso desde navegador Chrome',
    ip: '192.168.1.4',
    dispositivo: 'PC – Chrome 125',
    fecha: DateTime(2026, 6, 10, 8, 1),
  ),
  AuditRecord(
    id: 'aud2',
    usuario: 'Admin. Víctor Pari',
    usuarioRol: 'Administrador',
    accion: AuditActionType.create,
    modulo: 'Usuarios',
    detalle: 'Creación de usuario: Enf. Jorge Mamani (enf.mamani)',
    ip: '192.168.1.10',
    dispositivo: 'PC – Firefox 126',
    fecha: DateTime(2026, 6, 10, 7, 58),
  ),
  AuditRecord(
    id: 'aud3',
    usuario: 'Dr. Alejandro Martínez',
    usuarioRol: 'Médico',
    accion: AuditActionType.create,
    modulo: 'Historias Clínicas',
    detalle: 'HC creada para paciente Rosa Villanueva Quispe — HC-2024-04521',
    ip: '192.168.1.4',
    dispositivo: 'PC – Chrome 125',
    fecha: DateTime(2026, 6, 10, 8, 15),
  ),
  AuditRecord(
    id: 'aud4',
    usuario: 'Enf. Carmen Ramos',
    usuarioRol: 'Enfermero/a',
    accion: AuditActionType.edit,
    modulo: 'Historias Clínicas',
    detalle: 'Signos vitales actualizados — HC Juan Condori Mamani',
    ip: '192.168.1.7',
    dispositivo: 'Tablet – Safari 17',
    fecha: DateTime(2026, 6, 10, 8, 32),
  ),
  AuditRecord(
    id: 'aud5',
    usuario: 'Adm. Luis Torres',
    usuarioRol: 'Administrativo',
    accion: AuditActionType.logout,
    modulo: 'Sistema',
    detalle: 'Cierre de sesión manual',
    ip: '192.168.1.9',
    dispositivo: 'PC – Edge 125',
    fecha: DateTime(2026, 6, 10, 8, 45),
  ),
  AuditRecord(
    id: 'aud6',
    usuario: 'Admin. Víctor Pari',
    usuarioRol: 'Administrador',
    accion: AuditActionType.edit,
    modulo: 'Roles y Permisos',
    detalle: 'Permisos del rol Enfermero/a actualizados — módulo Telemedicina',
    ip: '192.168.1.10',
    dispositivo: 'PC – Firefox 126',
    fecha: DateTime(2026, 6, 10, 9, 5),
  ),
  AuditRecord(
    id: 'aud7',
    usuario: 'Dra. Patricia Quispe',
    usuarioRol: 'Médico',
    accion: AuditActionType.export,
    modulo: 'Reportes',
    detalle: 'Exportación PDF de Reporte de Consultas — Junio 2026',
    ip: '192.168.1.5',
    dispositivo: 'PC – Chrome 125',
    fecha: DateTime(2026, 6, 10, 9, 20),
  ),
  AuditRecord(
    id: 'aud8',
    usuario: 'Sistema',
    usuarioRol: 'Sistema',
    accion: AuditActionType.login,
    modulo: 'Sistema',
    detalle: 'Intento fallido de inicio de sesión — usuario desconocido (3 intentos)',
    ip: '200.45.123.88',
    dispositivo: 'Desconocido',
    fecha: DateTime(2026, 6, 10, 9, 47),
  ),
  AuditRecord(
    id: 'aud9',
    usuario: 'Admin. Víctor Pari',
    usuarioRol: 'Administrador',
    accion: AuditActionType.edit,
    modulo: 'Usuarios',
    detalle: 'Estado de usuario Tec. Rosa Ccopa cambiado a Suspendido',
    ip: '192.168.1.10',
    dispositivo: 'PC – Firefox 126',
    fecha: DateTime(2026, 6, 10, 10, 12),
  ),
  AuditRecord(
    id: 'aud10',
    usuario: 'Dr. Roberto Flores',
    usuarioRol: 'Médico',
    accion: AuditActionType.aprobar,
    modulo: 'Recetas',
    detalle: 'Receta electrónica firmada — RX-2026-08821 para María Luque',
    ip: '192.168.1.6',
    dispositivo: 'PC – Chrome 125',
    fecha: DateTime(2026, 6, 10, 10, 30),
  ),
  AuditRecord(
    id: 'aud11',
    usuario: 'Aud. Ana Catacora',
    usuarioRol: 'Auditor',
    accion: AuditActionType.view,
    modulo: 'Auditoría',
    detalle: 'Consulta de historial de auditoría — rango Mayo–Junio 2026',
    ip: '192.168.1.12',
    dispositivo: 'PC – Chrome 125',
    fecha: DateTime(2026, 6, 10, 11, 0),
  ),
  AuditRecord(
    id: 'aud12',
    usuario: 'Admin. Víctor Pari',
    usuarioRol: 'Administrador',
    accion: AuditActionType.create,
    modulo: 'Establecimientos',
    detalle: 'Nuevo establecimiento registrado: P.S. Azángaro (REP-2303-022)',
    ip: '192.168.1.10',
    dispositivo: 'PC – Firefox 126',
    fecha: DateTime(2026, 6, 9, 15, 30),
  ),
];
